### ISSUE TITLE
Partial Views / Same Folder

### ISSUE THREAD

**Issue by Cable11** [soundaranbu/RazorTemplating#13]
Greetings,

I have a view with a layout, using a partial view located in the same folder as the view using it

View - /Views/Reports/Opportunities.cshtml
Partial - /Views/Reports/_opportunity.cshtml
Layout - /Shared/Email.cshtml 

But I get the following error - 

InvalidOperationException: The partial view '_opportunity' was not found. The following locations were searched: /Views/_opportunity.cshtml /Views/Shared/_opportunity.cshtml. 

We have multiple partials for that view we use conditionally. 

I can move the partials to the shared directory which makes it work (not a big deal), just wondering if this behavior is by design, can be addressed via a settings, etc.

**Comment by soundaranbu** [comment]
Hi @Cable11, I'll try this out & let you know.

**Comment by soundaranbu** [comment]
I looked at this... it's already working with the views & partial views in the same folder. Kindly refer to the test case here
https://github.com/soundaranbu/RazorTemplating/blob/d63d017373360da3573499b43267a7a5c82f501f/test/Razor.Templating.Core.Test/RazorViewToStringRendererTest.cs#L23

and the view file used in the above test case can be found here

https://github.com/soundaranbu/RazorTemplating/tree/master/examples/Templates/ExampleAppRazorTemplates/Views

Let me know if that helps.

**Comment by Cable11** [comment]
Here is a quick test project to demonstrate. The view in the razor class library works fine in the web app, can't be found in the console app. 

It does work if located in the shared directory (also included in attached proj)
[WebApplication1.zip](https://github.com/soundaranbu/RazorTemplating/files/5749497/WebApplication1.zip)
.

**Comment by soundaranbu** [comment]
Hi @Cable11, I checked your sample. Add extension to your partial views, then it will work.
Change `@await Html.PartialAsync("_testPartial")` to `@await Html.PartialAsync("_testPartial.cshtml")`

P.S: I'm not sure how it works without extension in web app as I haven't gone into the internals of Razor SDK yet. But adding the file extension works in both web & console app.

**Comment by Cable11** [comment]
Ok - thanks. That was the issue at hand - having to change the logic that previously exists to use your package (when it works normally without using the .cshtml). 

Thanks for adding it to your list! :-)

**Comment by soundaranbu** [comment]
Unfortunately, this couldn't be achieved. Any community PR is welcome. Until then, please use the workaround described here https://github.com/soundaranbu/RazorTemplating/issues/13#issuecomment-752082884
