### ISSUE TITLE
Support for Azure Functions

### ISSUE THREAD

**Issue by awatertrevi** [soundaranbu/RazorTemplating#15]
Hi!

First off, thank you for the great library (makes things a lot simpler).
I would love to see support for Azure functions.

Currently when using it there I get the following exception:

`Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager'`

I currently managed to set it up using the following sample: https://github.com/EtiennePeeters/AzureFunctionsRazorEmailTemplateSample

Perhaps this can be integrated?

**Comment by soundaranbu** [comment]
Hi @awatertrevi, Thanks for taking your time to raise the issue & giving the solution as well. Definitely, I'll investigate into this & bring the support as soon as possible. 

Keep supporting :)

**Comment by soundaranbu** [comment]
Hi @awatertrevi , I've added support for azure functions in the preview release `v1.6.0-rc.2`.
If possible, kindly give it a try and let me know if that works or not.

**Comment by awatertrevi** [comment]
Hi @soundaranbu,

Apologies for my late reply. It works great 👍 !
