### ISSUE TITLE
[BUG] .NET 5 keeps increasing the memory usage when using razor files

### ISSUE THREAD

**Issue by Benexx** [soundaranbu/RazorTemplating#16]
Rendering the razor file keeps adding to the memory. For the example I use a file that generates an output of 10MB so you see the change in memory. When returning a View() there isn't a problem but when we use the RazorTemplateEngine it keeps adding to the memory. I tried to find the problem myself but I cannot find the issue.

**Test1**
When using Test1() the memory increases but is stable afterwards. Same for every other view rendered by .NET
![image](https://user-images.githubusercontent.com/2852986/108215016-1f748c00-7131-11eb-85c1-75c6e7b8cfc0.png)

**Test2**
When using Test2() the memory keeps increasing. Every snapshot is taken a after calling the test again.
![image](https://user-images.githubusercontent.com/2852986/108213552-74af9e00-712f-11eb-9e43-39be2aebea23.png)

and the diff of snapshot #7:
![image](https://user-images.githubusercontent.com/2852986/108213909-cf48fa00-712f-11eb-995d-f28152533721.png)

Startup.cs
``` C#
public void ConfigureServices([NotNull] IServiceCollection services)
  {
    // Some code

    services.AddRazorTemplating();
  }
```

Test.cshtml
``` Razor
@{
    Layout = null;
    var array = Enumerable.Repeat("A", 10000000); // 10MB string, we need to see it in memory
}

<div>
    @string.Concat(array)
</div>
```

TestController.cs
``` C#
public class TestController : Controller {
    public async Task<IActionResult> Test1()
    {
        return View("~/Views/Shared/Test.cshtml");
    }

    public async Task<IActionResult> Test2()
    {
        var html = await RazorTemplateEngine.RenderAsync("~/Views/Shared/Test.cshtml");

        return Ok("Done");
    }
}
```

**Comment by soundaranbu** [comment]
Interesting! I'll try to replicate & fix the issue.
Thanks for taking your time to debug & give detailed information.

**Comment by soundaranbu** [comment]
Hi @Benexx , I've fixed the issue. If possible you can checkout the latest master & test. Otherwise, I'll be releasing a preview version this weekend anyway. You can test using that. Thanks

**Comment by Benexx** [comment]
A thanks! I'll test it maybe this weekend or else on Monday! Thanks for the quick response!

**Comment by Benexx** [comment]
I have tested the memory usage and the problem seems to be solved! Thanks again for the quick response!

**Comment by soundaranbu** [comment]
That's good to know! I'll make a release for this fix

**Comment by soundaranbu** [comment]
**Update:** 
New version [v1.5.0](https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.5.0) with the fix has been released 
A much thanks to @Benexx for spotting this issue 💯🥇
