### ISSUE TITLE
Convert just partialview

### ISSUE THREAD

**Issue by mauricioferrazs** [soundaranbu/RazorTemplating#17]
Hello, I would like to know if it is possible to convert only the content of a partial view to a string?

I did a test here but it converts the entire page.

Thanks.

**Comment by mauricioferrazs** [comment]
Sorry man, I found in closed issue.

@{
    Layout = "_Layout";
}

This is worked thanks.

**Comment by soundaranbu** [comment]
Glad that you found the answer!
