### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by soundaranbu** [soundaranbu/RazorTemplating#20]

**Comment by soundaranbu** [comment]
Asked for help to the ASP.NET Core team as there's a breaking change to our library with the introduction of https://github.com/aspnet/Announcements/issues/459
Help Link:
https://github.com/dotnet/aspnetcore/issues/31578#issuecomment-841066601

**Comment by soundaranbu** [comment]
Found an alternative way to fix on our own
https://github.com/dotnet/aspnetcore/issues/31578#issuecomment-841834166

**Comment by litan1106** [comment]
@soundaranbu any plan on the .net 6 support? the .net6 RTM will be on Nov 2021

**Comment by soundaranbu** [comment]
Yes! Right now v1.5.0 works with  .NET 6 preview versions. But planning for v1.6.0 that has .NET 6 as base version.

**Comment by soundaranbu** [comment]
New preview version `v1.7.0-preview.1` released with .NET 6 support https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.7.0-preview.1
Kindly try it & let me know if there are any issues.

**Comment by soundaranbu** [comment]
Support for .NET 6 is now released as stable version `1.7.0`.
https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.7.0

Users of .NET 5 upgrading to .NET 6 should be using `v1.7.0`
Thanks!
