### ISSUE TITLE
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Runtime

### ISSUE THREAD

**Issue by eb-mikegorecki** [soundaranbu/RazorTemplating#27]
Hello,

Loving the easy implementation of this library so far. I am able to get the project to work locally. When I do a docker build I am running into this error. 

I currently have a console application project set up like this.

Email.sln
------------ Template.project
---------------- Templates
-------------------- TestTemplate.cshtml
-------------------- TestTemplateModel.cs  
------------ ConsoleApplication.project
-------------------- Service
Dockerfile

```CS
Unhandled exception. System.BadImageFormatException: 
Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution. 
They can only be loaded in the Reflection-only loader context. (0x80131058)

File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: 
Cannot load a reference assembly for execution.
```

If I add the nuget to the project at all I get this error when I start my container.

My dockerfile looks like this.

```DOCKERFILE
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

WORKDIR /app
COPY src/myapp/dist/* /app/

ENTRYPOINT ["dotnet", "myapp.dll"]
```

I am trying to build it on .net core 5.0. Any thoughts?

**Comment by soundaranbu** [comment]
Hi @eb-mikegorecki ..I'll try it & let you know. Between what version of the library are you using?

**Comment by eb-mikegorecki** [comment]
I tried between version 1.3.0 and latest. Pretty much anything that supported dotnet 5.

**Comment by soundaranbu** [comment]
Hi @eb-mikegorecki, I've committed [dockerfile](https://github.com/soundaranbu/RazorTemplating/blob/master/examples/Console/ExampleConsoleApp.Net5_0/Dockerfile) for [example console project](https://github.com/soundaranbu/RazorTemplating/tree/master/examples/Console/ExampleConsoleApp.Net5_0) in .NET 5. 

From the repository root directory, run this command to build the image
```bash
sudo docker build . -f "examples/Console/ExampleConsoleApp.Net5_0/Dockerfile" -t "razor-templating"
```
Run the image
```bash
sudo docker run razor-templating
```

Here's the output
![image](https://user-images.githubusercontent.com/29944019/126903012-fbdfbdc5-63f3-42d9-9997-0b9dc5361b37.png)

Give it a try & let me know. Thanks!

**Comment by eb-mikegorecki** [comment]
Awesome. This cleared my issue. Not sure what I was doing wrong before. I was building/releasing to a dist folder. Then copying the dist folder to the container and building the container in my CI/CD process.

Anyways, thanks for the help!
