### ISSUE TITLE
System.InvalidOperationException issue in 1.6

### ISSUE THREAD

**Issue by VictorDevmetro** [soundaranbu/RazorTemplating#30]
/* CS*/
return await RazorTemplateEngine.RenderAsync($"~/Views/{rendererActionName}.cshtml", viewModel, viewData);

/*CSHTML*/
@model ForgotPasswordEmail

This cimple code genereate exception **"System.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'EmailTemplates.ViewModels.ForgotPasswordEmail', but this ViewDataDictionary instance requires a model item of type 'EmailTemplates.ViewModels.ForgotPasswordEmail'."**

PS: works refecly in prev version (1.5)

**Comment by soundaranbu** [comment]
Thanks, I'll take a look.

**Comment by soundaranbu** [comment]
Hi @VictorDevmetro , When we remove `RazorTemplateEngine.Initialize();` from your Program.cs, the error is gone. The library creates the cache itself when it's run for the first time. So you can safely remove it. 

I'll investigate why it's throwing error in your use case in `v1.6.0`

**Comment by soundaranbu** [comment]
**Update:** Problem is specific to worker service when `RazorTemplateEngine.Initialize();` is called in bootstrap code in `v1.6.0`. It's advised to remove this line until a fix is released. 
Please note, removing this line doesn't make any big difference. The core feature will work as before.

Thanks!

**Comment by VictorDevmetro** [comment]
Thx. It fixed my problem.

**Comment by soundaranbu** [comment]
Issue fixed in `v1.7.0` in .NET 6
