### ISSUE TITLE
Running asp.net core project with dotnet watch run no longer detects changes to .cshtml files

### ISSUE THREAD

**Issue by juliocdeleonb** [soundaranbu/RazorTemplating#31]
I'm having this issue running version 1.6.0 with .NET 5. Functionality wise, there is no problem with the component, however, when running the project via dotnet watch run, it no longer detects changes to .cshtml files. Code files .cs works fine. In order to rule out if it is my project alone, I created a new asp.net core Web App using the Visual Studio template and without any modifications at all, ran the dotnet command, edited and saved the Index.cshtml file and the changes were detected. I stopped the process first, then added the Razor.Templating.Core nuget package only and once more, ran the dotnet command, modified Index.cshtml, saved it, but the changes were not picked up. I really appreciate if you can look into this. Thank you.

**Comment by soundaranbu** [comment]
Hi @juliocdeleonb , I'm unable to replicate this issue. You can try this sample project & let me know https://github.com/soundaranbu/RazorTemplating/tree/v1.6.0/examples/Mvc/ExampleWebApp.Net5_0

I tried in both Visual Studio 2019 & `dotnet watch`. Whenever I changed something in the view, it got reflected on reloading the page.

**Comment by soundaranbu** [comment]
Closing as it's not reproducible. Feel free to re-open if need to discuss further. Thanks!
