### ISSUE TITLE
Pass ViewBag object

### ISSUE THREAD

**Issue by glararan** [soundaranbu/RazorTemplating#36]
Hi,

I would like to know how to pass ViewBag object? There is no documentation nor example contains ViewBag usage.

Should I pass ViewData dictionary and access it via ViewBag?

Asking as I am migrating from RazorLight.

EDIT:
Rather than starting new issue I will ask here.. I have dir EmailTemplates in root. However inside e.g. /EmailTemplates/Registration I am using _Layout located in /EmailTemplates/_Layout.. I cant figure out how to get it working. Tried Layout change to /EmailTemplates/_Layout not works.

EDIT 2:
Layout handled via workaround 
```
services.Configure<RazorViewEngineOptions>(options =>
            {
                options.ViewLocationFormats.Add("/EmailTemplates/_Layout.cshtml");
            });
```

EDIT 3:
Seems to work with ViewBag following code
`await RazorTemplateEngine.RenderAsync($"template.cshtml", model, new Dictionary<string, object>(viewBag));`

**Comment by soundaranbu** [comment]
Hi @glararan, thanks for reporting your issue. Yes. Both `ViewData` and `ViewBag` should be passed in the same dictionary object. I'll add it in the documentation. 

Thanks :)

**Comment by soundaranbu** [comment]
I've updated documentation. Feel free to reopen if you find any issues. Thanks!
