### ISSUE TITLE
AddRazorTemplating Not Thread-Safe

### ISSUE THREAD

**Issue by dradovic** [soundaranbu/RazorTemplating#46]
Occasionally, I see the following call-stack in our CI:

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Razor.Templating.Core.RazorViewToStringRendererFactory.<>c.<CreateRendererServiceScopeFactory>b__4_0(ApplicationPartManager manager)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.ConfigureApplicationPartManager(IMvcCoreBuilder builder, Action`1 setupAction)
   at Razor.Templating.Core.RazorViewToStringRendererFactory.CreateRendererServiceScopeFactory()
   at Razor.Templating.Core.RazorTemplateEngine.GetRendererServiceScopeFactory()
   at Razor.Templating.Core.RazorTemplateEngine.Initialize()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddRazorTemplating(IServiceCollection services)
```

We have many tests in our CI that are executed in parallel so there might be a race condition here. Do you think you are able to make `AddRazorTemplating` thread-safe?

**Comment by soundaranbu** [comment]
Hi @dradovic, Thanks for reporting the issue.

`RazorTemplateEngine` was designed to be a single instance application-wide using a static property. Because recreating the template engine every time is an expensive operation.

But I will see if I can tweak this to make it thread-safe.

Until then you can either move the initialization to the global level or run the test cases sequentially.

**Comment by dradovic** [comment]
Thanks for looking into this. Let me know how it goes.

**Comment by pbolduc** [comment]
Hi, I have a pull request #48 that should hopefully address your concerns. Can you take a look and provide any feedback to changes for your use case.

**Comment by soundaranbu** [comment]
Hey @dradovic, please try the fix in [v1.8.0](https://github.com/soundaranbu/Razor.Templating.Core/releases/tag/v1.8.0-rc.1) and let us know!

**Comment by pbolduc** [comment]
You will want to move away from the static `RazorTemplateEngine` class and inject in a `IRazorTemplateEngine` instance to your services.  the `RazorTemplateEngine` static class maintains an internal lazy created instance of `IRazorTemplateEngine`. If you attempt to use the `AddRazorTemplating()` function after rendering a view using the static class, the internal instance will be reset to uninitialed. This re-initialization may not be fully thread-safe in rapidly executing unit tests.  Injecting a `IRazorTemplateEngine` interface instance will also help mocking of this service with something like Moq.

**Comment by dradovic** [comment]
I’m currently traveling but I’ll have a look latest tomorrow. Thanks.

**Comment by dradovic** [comment]
So I have upgraded to RC1 and I've switched to using the injected `IRazorTemplateEngine`'s `RenderAsync` method instead of the static one. Outcome: the rendered HTML looks fine (I didn't spot any regression) and I've retriggered the CI for 10x without having any concurrency issues.
So it seems you guys made a great job! Thank you very much!

@soundaranbu So, I guess you'll release 1.8.0 soon?

**Comment by soundaranbu** [comment]
Hi @dradovic, glad that it works for you. All thanks to @pbolduc for his contribution :) 

Yes, I'll release v1.8.0 soon. Probably in a week or so.

**Comment by dradovic** [comment]
I'm still interested and waiting for an official release :)

**Comment by soundaranbu** [comment]
Hi @dradovic, I understand that it's overdue. The last several weeks have been hectic for me. Please expect it this weekend. Thanks :)

**Comment by soundaranbu** [comment]
Hi @dradovic, stable version is now released https://www.nuget.org/packages/Razor.Templating.Core/1.8.0

Thanks!
