### ISSUE TITLE
The tests failed

### ISSUE THREAD

**Issue by litan1106** [soundaranbu/RazorTemplating#6]
The examples ran fine but the tests failed.

![image](https://user-images.githubusercontent.com/1310539/91232242-97fb1280-e6e3-11ea-936d-86179b499104.png)

**Comment by litan1106** [comment]
Never mind, the tests ran fine on dotnet but failed in JetBrains Rider and Visual Studio with Resharper because the Rider TestRunner is located in a different location.
```
C:\Users\NOBODY\AppData\Local\JetBrains\Toolbox\apps\Rider\VERSION\lib\ReSharperHost\TestRunner\netcoreapp2.0
```

**Comment by soundaranbu** [comment]
Hi @litan1106 , Thanks for reporting the issue & fixing it as well. You're awesome! 
I'll review the changes, do some test & make a new release as soon as possible.

**Comment by litan1106** [comment]
> Hi @litan1106 , Thanks for reporting the issue & fixing it as well. You're awesome!
> I'll review the changes, do some test & make a new release as soon as possible.

Thanks for the great library. Best solution I have seen so far.

**Comment by litan1106** [comment]
> Hi @litan1106 , Thanks for reporting the issue & fixing it as well. You're awesome!
> I'll review the changes, do some test & make a new release as soon as possible.

@soundaranbu I am waiting for the new release.

**Comment by soundaranbu** [comment]
Hi @litan1106, I thought this issue is affecting only when working with the source code (running the test cases in Rider)... So I was waiting for any new changes to arrive... If it is an issue when using the library itself in projects, I'm making a new release right away

**Comment by soundaranbu** [comment]
Published new release. Thanks @litan1106 
https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.2.1
https://www.nuget.org/packages/Razor.Templating.Core/1.2.1
